import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { test } from "node:test";

const generated = [
  "generated/domain.ts",
  "generated/api.ts",
  "generated/schema.sql",
  "generated/migrations/0001_initial.sql",
  "generated/transactions.ts",
  "generated/idempotency.ts",
  "generated/migrations/0002_idempotency.sql",
  "generated/outbox.ts",
  "generated/migrations/0003_outbox.sql",
] as const;

test("all M4 generated outputs retain AIDL ownership markers", async () => {
  for (const path of generated) {
    const text = await readFile(path, "utf8");
    const prefix = path.endsWith(".ts") ? "//" : "--";
    assert.match(text, new RegExp(`^${prefix.replace("/", "\\/")} @generated by AIDL; ownership=aidl; sha256=[0-9a-f]{64}\\n`));
  }
});

test("canonical IR and plan are reproducible build inputs", async () => {
  const ir = JSON.parse(await readFile("build/canonical-ir.json", "utf8")) as { irVersion?: string };
  const plan = JSON.parse(await readFile("build/plan.json", "utf8")) as { planVersion?: string };
  assert.equal(ir.irVersion, "0.3.0");
  assert.ok(typeof plan.planVersion === "string");
});
