from __future__ import annotations

import hashlib
import os
import tempfile
from collections.abc import Mapping
from pathlib import Path, PurePosixPath


_MARKER_LABEL = "@generated by AIDL; ownership=aidl; sha256="
_SUPPORTED_SUFFIXES = {".ts": "//", ".sql": "--"}


class GeneratedOwnershipError(ValueError):
    pass


def _comment_prefix(path: str) -> str:
    suffix = PurePosixPath(path).suffix
    prefix = _SUPPORTED_SUFFIXES.get(suffix)
    if prefix is None:
        raise GeneratedOwnershipError(f"unsupported generated file type '{suffix or '<none>'}' for '{path}'")
    return prefix


def _validated_relative_path(path: str) -> PurePosixPath:
    candidate = PurePosixPath(path)
    if candidate.is_absolute() or not candidate.parts or candidate.parts[0] != "generated" or ".." in candidate.parts:
        raise GeneratedOwnershipError(f"generated path must stay under generated/: '{path}'")
    _comment_prefix(path)
    return candidate


def _digest(body: str) -> str:
    return hashlib.sha256(body.encode("utf-8")).hexdigest()


def mark_generated_file(path: str, body: str) -> str:
    """Return deterministic AIDL-owned content for one generated TypeScript or SQL file."""
    _validated_relative_path(path)
    if not isinstance(body, str):
        raise GeneratedOwnershipError(f"generated content for '{path}' must be text")
    prefix = _comment_prefix(path)
    return f"{prefix} {_MARKER_LABEL}{_digest(body)}\n{body}"


def validate_generated_file(path: str, content: str) -> None:
    """Reject content that is not intact and unambiguously owned by AIDL."""
    _validated_relative_path(path)
    prefix = _comment_prefix(path)
    first, separator, body = content.partition("\n")
    expected_start = f"{prefix} {_MARKER_LABEL}"
    if not separator or not first.startswith(expected_start):
        raise GeneratedOwnershipError(f"refusing to overwrite unowned generated file '{path}'")
    digest = first[len(expected_start):]
    if len(digest) != 64 or any(character not in "0123456789abcdef" for character in digest):
        raise GeneratedOwnershipError(f"refusing to overwrite damaged ownership marker in '{path}'")
    if digest != _digest(body):
        raise GeneratedOwnershipError(f"refusing to overwrite tampered generated file '{path}'")


def mark_generated_files(files: Mapping[str, str]) -> dict[str, str]:
    marked: dict[str, str] = {}
    for path in sorted(files):
        if path in marked:
            raise GeneratedOwnershipError(f"duplicate generated path '{path}'")
        marked[path] = mark_generated_file(path, files[path])
    return marked


def write_generated_files(root: Path, files: Mapping[str, str]) -> None:
    """Safely replace a complete marked file set after ownership preflight.

    All destination validation happens before staging or target mutation. Replacement failures
    restore every target already replaced during this call, so callers never need to repair a
    partially accepted generation manually.
    """
    root = Path(root)
    ordered: list[tuple[str, Path, str]] = []
    for relative in sorted(files):
        candidate = _validated_relative_path(relative)
        content = files[relative]
        validate_generated_file(relative, content)
        ordered.append((relative, root.joinpath(*candidate.parts), content))

    originals: dict[Path, bytes | None] = {}
    for relative, destination, _content in ordered:
        if destination.exists():
            existing = destination.read_text(encoding="utf-8")
            validate_generated_file(relative, existing)
            originals[destination] = destination.read_bytes()
        else:
            originals[destination] = None

    staged: dict[Path, Path] = {}
    try:
        for _relative, destination, content in ordered:
            destination.parent.mkdir(parents=True, exist_ok=True)
            descriptor, temporary = tempfile.mkstemp(prefix=f".{destination.name}.", dir=destination.parent)
            temporary_path = Path(temporary)
            staged[destination] = temporary_path
            with os.fdopen(descriptor, "w", encoding="utf-8", newline="") as handle:
                handle.write(content)
                handle.flush()
                os.fsync(handle.fileno())

        replaced: list[Path] = []
        try:
            for _relative, destination, _content in ordered:
                os.replace(staged[destination], destination)
                staged.pop(destination, None)
                replaced.append(destination)
        except Exception:
            for destination in reversed(replaced):
                original = originals[destination]
                if original is None:
                    destination.unlink(missing_ok=True)
                    continue
                descriptor, temporary = tempfile.mkstemp(prefix=f".{destination.name}.rollback.", dir=destination.parent)
                with os.fdopen(descriptor, "wb") as handle:
                    handle.write(original)
                    handle.flush()
                    os.fsync(handle.fileno())
                os.replace(temporary, destination)
            raise
    finally:
        for temporary in staged.values():
            temporary.unlink(missing_ok=True)
