from __future__ import annotations

import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

from tools import generate_m4
from tools.generated_ownership import (
    GeneratedOwnershipError,
    mark_generated_file,
    mark_generated_files,
    validate_generated_file,
    write_generated_files,
)


class GeneratedOwnershipTest(unittest.TestCase):
    def test_markers_are_deterministic_and_syntax_appropriate(self) -> None:
        ts = mark_generated_file("generated/domain.ts", "export type X = string;\n")
        sql = mark_generated_file("generated/schema.sql", "CREATE TABLE x(id text);\n")
        self.assertEqual(ts, mark_generated_file("generated/domain.ts", "export type X = string;\n"))
        self.assertTrue(ts.startswith("// @generated by AIDL; ownership=aidl; sha256="))
        self.assertTrue(sql.startswith("-- @generated by AIDL; ownership=aidl; sha256="))
        validate_generated_file("generated/domain.ts", ts)
        validate_generated_file("generated/schema.sql", sql)

    def test_m4_bundle_marks_every_m4_02_through_m4_07_output(self) -> None:
        generated_sets = (
            {"generated/domain.ts": "domain\n"},
            {"generated/api.ts": "api\n"},
            {"generated/schema.sql": "schema\n", "generated/migrations/0001_initial.sql": "m1\n"},
            {"generated/transactions.ts": "tx\n"},
            {"generated/idempotency.ts": "idem\n", "generated/migrations/0002_idempotency.sql": "m2\n"},
            {"generated/outbox.ts": "outbox\n", "generated/migrations/0003_outbox.sql": "m3\n"},
        )
        generators = tuple((lambda result: lambda _ir: result)(result) for result in generated_sets)
        with patch.object(generate_m4, "_GENERATORS", generators):
            files = generate_m4.generate_m4_files({"irVersion": "0.3.0"})
        self.assertEqual(
            set(files),
            {
                "generated/domain.ts",
                "generated/api.ts",
                "generated/schema.sql",
                "generated/migrations/0001_initial.sql",
                "generated/transactions.ts",
                "generated/idempotency.ts",
                "generated/migrations/0002_idempotency.sql",
                "generated/outbox.ts",
                "generated/migrations/0003_outbox.sql",
            },
        )
        for path, content in files.items():
            validate_generated_file(path, content)

    def test_regeneration_replaces_only_intact_aidl_owned_files(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            first = mark_generated_files({
                "generated/domain.ts": "first domain\n",
                "generated/schema.sql": "first schema\n",
            })
            write_generated_files(root, first)
            second = mark_generated_files({
                "generated/domain.ts": "second domain\n",
                "generated/schema.sql": "second schema\n",
            })
            write_generated_files(root, second)
            self.assertEqual((root / "generated/domain.ts").read_text(encoding="utf-8"), second["generated/domain.ts"])
            self.assertEqual((root / "generated/schema.sql").read_text(encoding="utf-8"), second["generated/schema.sql"])

    def test_unowned_target_is_rejected_before_any_target_changes(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            generated = root / "generated"
            generated.mkdir()
            domain = generated / "domain.ts"
            schema = generated / "schema.sql"
            domain.write_text(mark_generated_file("generated/domain.ts", "old domain\n"), encoding="utf-8")
            schema.write_text("-- maintained by a human\n", encoding="utf-8")
            before_domain = domain.read_bytes()
            before_schema = schema.read_bytes()
            proposed = mark_generated_files({
                "generated/domain.ts": "new domain\n",
                "generated/schema.sql": "new schema\n",
            })
            with self.assertRaisesRegex(GeneratedOwnershipError, "unowned"):
                write_generated_files(root, proposed)
            self.assertEqual(domain.read_bytes(), before_domain)
            self.assertEqual(schema.read_bytes(), before_schema)

    def test_tampered_target_is_rejected_before_any_target_changes(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            generated = root / "generated"
            generated.mkdir()
            domain = generated / "domain.ts"
            schema = generated / "schema.sql"
            domain.write_text(mark_generated_file("generated/domain.ts", "old domain\n"), encoding="utf-8")
            intact_schema = mark_generated_file("generated/schema.sql", "old schema\n")
            schema.write_text(intact_schema + "-- manual edit\n", encoding="utf-8")
            before_domain = domain.read_bytes()
            before_schema = schema.read_bytes()
            proposed = mark_generated_files({
                "generated/domain.ts": "new domain\n",
                "generated/schema.sql": "new schema\n",
            })
            with self.assertRaisesRegex(GeneratedOwnershipError, "tampered"):
                write_generated_files(root, proposed)
            self.assertEqual(domain.read_bytes(), before_domain)
            self.assertEqual(schema.read_bytes(), before_schema)

    def test_foreign_or_damaged_markers_are_rejected(self) -> None:
        body = "export type X = string;\n"
        foreign = "// @generated by Other; ownership=other; sha256=" + "0" * 64 + "\n" + body
        with self.assertRaisesRegex(GeneratedOwnershipError, "unowned"):
            validate_generated_file("generated/domain.ts", foreign)
        damaged = "// @generated by AIDL; ownership=aidl; sha256=xyz\n" + body
        with self.assertRaisesRegex(GeneratedOwnershipError, "damaged"):
            validate_generated_file("generated/domain.ts", damaged)


if __name__ == "__main__":
    unittest.main()
